module.exports = {
	extends: [
		'./es6.js',
		'plugin:jest-dom/recommended',
		'plugin:react/recommended',
		'plugin:react-hooks/recommended',
		'plugin:jsx-a11y/recommended',
	],
	rules: {
		'jsx-quotes': 'error',
		'no-extra-parens': 'off',
		'react/button-has-type': 'off',
		'react/display-name': 'error',
		'react-hooks/exhaustive-deps': 'off',
		'react/jsx-boolean-value': ['error', 'always'],
		'react/jsx-curly-brace-presence': 'off',
		'react/destructuring-assignment': ['error', 'always', { ignoreClassFields: true }],
		'react/jsx-filename-extension': ['warn', { extensions: ['.js', '.jsx', '.tsx'] }],
		'react/jsx-fragments': ['error', 'element'],
		'react/jsx-key': 'error',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-undef': 'error',
		'react/jsx-no-bind': [ 'error', {
			allowArrowFunctions: true,
		} ],
		'react/jsx-one-expression-per-line': 'off',
		'react/jsx-pascal-case': 'error',
		'react/jsx-props-no-spreading': 'off',
		'react/jsx-uses-react': 'error',
		'react/jsx-uses-vars': 'error',
		'react/jsx-wrap-multilines': ['error', { prop: 'ignore', arrow: 'ignore' }],
		'react/no-danger': 'off',
		'react/no-is-mounted': 'error',
		'react/no-this-in-sfc': 'off',
		'react/no-unknown-property': 'error',
		'react/prefer-stateless-function': 'error',
		'react/prop-types': 'off',
		'react/react-in-jsx-scope': 'error',
		'react/self-closing-comp': 'error',
		'react/sort-comp': ['error', {
			order: [
				'static-methods',
				'instance-variables',
				'lifecycle',
				'everything-else',
				'render',
			],
		}],
	},
}
